-- CREATE TABLE `NOTICE` (
-- 	`NOTICE_ID`	VARCHAR(255)	NOT NULL,
-- 	`CONTENTS`	VARCHAR(255)	NULL,
-- 	`WRITER`	VARCHAR(255)	NULL
-- );

-- CREATE TABLE `VISITOR` (
-- 	`VISITOR_ID`	VARCHAR(255)	NOT NULL,
-- 	`NOTICE_ID`	VARCHAR(255)	NOT NULL,
-- 	`VISITOR_NAME`	VARCHAR(255)	NULL
-- );

-- INSERT 기본 구문 
-- INSERT INTO table_name 
-- (column1, column2, column3, ...)
-- VALUES 
-- (value1, value2, value3, ...);

--  공지 table 내 value값 넣기
INSERT INTO NOTICE 
(NOTICE_ID, CONTENTS, WRITER)
VALUES 
('NOTICE_01', '서비스 점검 안내', '관리자');

INSERT INTO VISITOR 
(VISITOR_ID, NOTICE_ID, VISITOR_NAME)
VALUES 
('VISITE01', 'NOTICE_01', '홍길동');

--  <QUEST> NOTICE table 내 value 추가
INSERT INTO NOTICE 
(NOTICE_ID, CONTENTS, WRITER)
VALUES 
('NOTICE_05', '서비스 이용약관 변경 안내', '운영팀');

--  <QUEST> VISITOR table 내 value 추가
INSERT INTO VISITOR 
(VISITOR_ID, NOTICE_ID, VISITOR_NAME)
VALUES 
('VISITE10', 'NOTICE_05', '강수민');
INSERT INTO VISITOR 
(VISITOR_ID, NOTICE_ID, VISITOR_NAME)
VALUES 
('VISITE11', 'NOTICE_05', '백지영');
INSERT INTO VISITOR 
(VISITOR_ID, NOTICE_ID, VISITOR_NAME)
VALUES 
('VISITE12', 'NOTICE_05', '박정희');

--  <QUEST> TABLE 확인하기
SELECT *
FROM NOTICE;

SELECT *
FROM VISITOR;