CREATE TABLE `SUBJECT` (
	`SUBJECT_ID`	VARCHAR(255)	NOT NULL,
	`SUBJECT`	VARCHAR(255)	NULL,
	`WRITER`	VARCHAR(255)	NULL
);

CREATE TABLE `REVIEW` (
	`REVIEW_ID`	VARCHAR(255)	NOT NULL,
	`SUBJECT_ID`	VARCHAR(255)	NOT NULL,
	`REVIEW`	VARCHAR(255)	NULL
);

ALTER TABLE `SUBJECT` ADD CONSTRAINT `PK_SUBJECT` PRIMARY KEY (
	`SUBJECT_ID`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`REVIEW_ID`,
	`SUBJECT_ID`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_SUBJECT_TO_REVIEW_1` FOREIGN KEY (
	`SUBJECT_ID`
)
REFERENCES `SUBJECT` (
	`SUBJECT_ID`
);

