CREATE TABLE `HOBBY` (
	`USER_HOBBY_ID`	VARCHAR(50)	NOT NULL,
	`USER_HOBBY`	VARCHAR(255)	NULL
);

CREATE TABLE `CONNECT` (
	`USER_CONNECT_ID`	VARCHAR(50)	NOT NULL,
	`USER_SEX`	VARCHAR(50)	NOT NULL,
	`USER_NAME`	VARCHAR(255)	NULL,
	`USER_AGE`	VARCHAR(255)	NULL,
	`USER_NUMBER`	VARCHAR(255)	NULL,
	`USER_EMAIL`	VARCHAR(255)	NULL
);

CREATE TABLE `ADDRESS` (
	`USER_ADDRESS_ID`	VARCHAR(50)	NOT NULL,
	`USER_ADDRESS`	VARCHAR(255)	NULL
);

CREATE TABLE `USER_INFORMATIONS` (
	`USER_INFORMATIONS_ID`	VARCHAR(50)	NOT NULL,
	`USER_CONNECT_ID`	VARCHAR(50)	NOT NULL,
	`USER_ADDRESS_ID`	VARCHAR(50)	NOT NULL,
	`USER_HOBBY_ID`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `SEX` (
	`USER_SEX_ID`	VARCHAR(50)	NOT NULL,
	`USER_SEX`	VARCHAR(255)	NULL
);

ALTER TABLE `HOBBY` ADD CONSTRAINT `PK_HOBBY` PRIMARY KEY (
	`USER_HOBBY_ID`
);

ALTER TABLE `CONNECT` ADD CONSTRAINT `PK_CONNECT` PRIMARY KEY (
	`USER_CONNECT_ID`,
	`USER_SEX`
);

ALTER TABLE `ADDRESS` ADD CONSTRAINT `PK_ADDRESS` PRIMARY KEY (
	`USER_ADDRESS_ID`
);

ALTER TABLE `USER_INFORMATIONS` ADD CONSTRAINT `PK_USER_INFORMATIONS` PRIMARY KEY (
	`USER_INFORMATIONS_ID`,
	`USER_CONNECT_ID`,
	`USER_ADDRESS_ID`,
	`USER_HOBBY_ID`
);

ALTER TABLE `SEX` ADD CONSTRAINT `PK_SEX` PRIMARY KEY (
	`USER_SEX_ID`
);

ALTER TABLE `CONNECT` ADD CONSTRAINT `FK_SEX_TO_CONNECT_1` FOREIGN KEY (
	`USER_SEX`
)
REFERENCES `SEX` (
	`USER_SEX_ID`
);

ALTER TABLE `USER_INFORMATIONS` ADD CONSTRAINT `FK_CONNECT_TO_USER_INFORMATIONS_1` FOREIGN KEY (
	`USER_CONNECT_ID`
)
REFERENCES `CONNECT` (
	`USER_CONNECT_ID`
);

ALTER TABLE `USER_INFORMATIONS` ADD CONSTRAINT `FK_ADDRESS_TO_USER_INFORMATIONS_1` FOREIGN KEY (
	`USER_ADDRESS_ID`
)
REFERENCES `ADDRESS` (
	`USER_ADDRESS_ID`
);

ALTER TABLE `USER_INFORMATIONS` ADD CONSTRAINT `FK_HOBBY_TO_USER_INFORMATIONS_1` FOREIGN KEY (
	`USER_HOBBY_ID`
)
REFERENCES `HOBBY` (
	`USER_HOBBY_ID`
);

