CREATE TABLE `COMPANY` (
	`CARS_COMPANYS_ID`	VARCHAR(50)	NOT NULL,
	`CARS_COMPANYS`	VARCHAR(255)	NULL
);

CREATE TABLE `CARS_NAME` (
	`CARS_NAME_ID`	VARCHAR(50)	NOT NULL,
	`CARS_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `YEARS` (
	`CARS_YEARS_ID`	VARCHAR(50)	NOT NULL,
	`CARS_YEARS`	VARCHAR(255)	NULL
);

CREATE TABLE `OPTIONS` (
	`CARS_OPTIONS_ID`	VARCHAR(50)	NOT NULL,
	`CARS_OPTIONS`	VARCHAR(255)	NULL
);

CREATE TABLE `CARS_INFORMATIONS` (
	`CARS_INFOS_ID`	VARCHAR(50)	NOT NULL,
	`CARS_COMPANYS_ID`	VARCHAR(50)	NOT NULL,
	`CARS_NAME_ID`	VARCHAR(50)	NOT NULL,
	`CARS_YEARS_ID`	VARCHAR(50)	NOT NULL,
	`CARS_OPTIONS_ID`	VARCHAR(50)	NOT NULL
);

ALTER TABLE `COMPANY` ADD CONSTRAINT `PK_COMPANY` PRIMARY KEY (
	`CARS_COMPANYS_ID`
);

ALTER TABLE `CARS_NAME` ADD CONSTRAINT `PK_CARS_NAME` PRIMARY KEY (
	`CARS_NAME_ID`
);

ALTER TABLE `YEARS` ADD CONSTRAINT `PK_YEARS` PRIMARY KEY (
	`CARS_YEARS_ID`
);

ALTER TABLE `OPTIONS` ADD CONSTRAINT `PK_OPTIONS` PRIMARY KEY (
	`CARS_OPTIONS_ID`
);

ALTER TABLE `CARS_INFORMATIONS` ADD CONSTRAINT `PK_CARS_INFORMATIONS` PRIMARY KEY (
	`CARS_INFOS_ID`,
	`CARS_COMPANYS_ID`,
	`CARS_NAME_ID`,
	`CARS_YEARS_ID`,
	`CARS_OPTIONS_ID`
);

ALTER TABLE `CARS_INFORMATIONS` ADD CONSTRAINT `FK_COMPANY_TO_CARS_INFORMATIONS_1` FOREIGN KEY (
	`CARS_COMPANYS_ID`
)
REFERENCES `COMPANY` (
	`CARS_COMPANYS_ID`
);

ALTER TABLE `CARS_INFORMATIONS` ADD CONSTRAINT `FK_CARS_NAME_TO_CARS_INFORMATIONS_1` FOREIGN KEY (
	`CARS_NAME_ID`
)
REFERENCES `CARS_NAME` (
	`CARS_NAME_ID`
);

ALTER TABLE `CARS_INFORMATIONS` ADD CONSTRAINT `FK_YEARS_TO_CARS_INFORMATIONS_1` FOREIGN KEY (
	`CARS_YEARS_ID`
)
REFERENCES `YEARS` (
	`CARS_YEARS_ID`
);

ALTER TABLE `CARS_INFORMATIONS` ADD CONSTRAINT `FK_OPTIONS_TO_CARS_INFORMATIONS_1` FOREIGN KEY (
	`CARS_OPTIONS_ID`
)
REFERENCES `OPTIONS` (
	`CARS_OPTIONS_ID`
);

